### ISSUE TITLE
@aws-sdk/client-ssm@^3.391.0 SSMClient.send does not accept GetParameterCommand

### ISSUE THREAD

**Issue by sfosterDunelm** [aws/aws-sdk-js-v3#5112]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

When upgrading the `@aws-sdk/client-ssm` package from v3.388.0 to v3.391.0 there is now a type error using a `GetParameterCommand` when using the `send` method from the client. This also occurs when trying to use the `GetSecretValueCommand` when using the `send` method of the `SecretsManagerClient`. I would guess that the two issues are related.

### SDK version number

@aws-sdk/client-ssm@^3.391.0, @aws-sdk/client-secrets-manager@^3.391.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

node v18.17.1

### Reproduction Steps

```ts
import { SSMClient, GetParameterCommand } from '@aws-sdk/client-ssm'

import type { GetParameterCommandInput } from '@aws-sdk/client-ssm'

const client = new SSMClient({})
const input: GetParameterCommandInput = {
  Name: 'parameterId',
}
const command = new GetParameterCommand(input)
client.send(command)
```

### Observed Behavior

When running `tsc --noEmit` it results in this error:
```bash
foo/bug.ts(10,13): error TS2345: Argument of type 'GetParameterCommand' is not assignable to parameter of type 'Command<ServiceInputTypes, GetParameterCommandInput, ServiceOutputTypes, GetParameterCommandOutput, SmithyResolvedConfiguration<...>>'.
         Types of property 'resolveMiddleware' are incompatible.
           Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SSMClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: SmithyResolvedConfiguration<HttpHandlerOptions>, options: any) => Handler<...>'.
             Types of parameters 'clientStack' and 'stack' are incompatible.
               Type 'import("/foo/node_modules/@smithy/middleware-endpoint/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceInputTypes, import("/foo...' is not assignable to type 'import("/foo/node_modules/@smithy/types/dist-types/middleware").MiddlewareStack<import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceInputTypes, import("/foo/node_modules/@aws-sdk/client-ssm/d...'.
                 Types of property 'concat' are incompatible.
                   Type '<InputType extends import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceInputTypes, OutputType extends import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceOutputTypes>(from: import("/foo...' is not assignable to type '<InputType extends import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceInputTypes, OutputType extends import("/foo/node_modules/@aws-sdk/client-ssm/dist-types/SSMClient").ServiceOutputTypes>(from: import("/foo...'. Two different types with this name exist, but they are unrelated.
                     Types of parameters 'from' and 'from' are incompatible.
                       Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
                         Types of property 'addRelativeTo' are incompatible.
                           Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
                             Types of parameters 'middleware' and 'middleware' are incompatible.
                               Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                                 Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                                   Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                                     Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                                       Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                                         Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                                           Types of property 'output' are incompatible.
                                             Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                               'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'ServiceOutputTypes'.
                                                 Type 'AddTagsToResourceCommandOutput' is not assignable to type 'OutputType'.
                                                   'AddTagsToResourceCommandOutput' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'ServiceOutputTypes'.
```

### Expected Behavior

The ssm client should be able to accept commands in it's send method.

### Possible Solution

I would guess that this is to do with the smithy version bump as it seems to relate to command types in general but I don't know enough about that package to be sure.

### Additional Information/Context

This is using version 5.1.3 of typescript

**Comment by jacobemerick** [comment]
+1, seeing this issue with client-cognito-identity-provider, client-dynamodb, client-s3 -- 3.395 on all. typescript 5.1.6, node 18.17.1

**Comment by yenfryherrerafeliz** [comment]
Hi @sfosterDunelm, @jacobemerick, I do not know what could causing this issue at your end. I just tried to reproduce this on my local env and everything works fine. Are you using pnpm?, or would it be possible for you to start a project from scratch and test to see if you observe the same behavior?.

Steps to reproduce:
- Create a new project: ```npm init -y```
- Install the dependencies: ```npm install @aws-sdk/client-ssm```
- Create a src/index.ts folder and file
- I used the code below:
```ts
import {SSMClient, GetParameterCommand} from "@aws-sdk/client-ssm";

import type { GetParameterCommandInput } from "@aws-sdk/client-ssm";

const client = new SSMClient({
    region: "us-east-2"
});
const input: GetParameterCommandInput = {
    Name: "test-input"
};
const cmd = new GetParameterCommand(input);
(async () => {
    const response = await client.send(cmd);

    console.log(response)
})();
```
- Ran tsc and compiled my ts file just fine.

Please let  me know.

Thanks!

**Comment by jacobemerick** [comment]
Wiped our node_modules && yarn.lock and started fresh, seems to be working fine now. Might have been a forced resolution to client-lambda@3.370 due to an outdated package, also removed that. Thanks for the quick response 🙌

**Comment by yenfryherrerafeliz** [comment]
@jacobemerick you are very welcome. I am going to resolve this issue, but if you happen to need anything else that we can help with, feel free of opening a new report. 

Thanks!
