### ISSUE TITLE
type checking error after updating from 3.42.0

### ISSUE THREAD

**Issue by Sufiane** [aws/aws-sdk-js-v3#3330]
## Describe the bug
After updating to v3.51.0 from v3.42.0, when doing some type checking i get the following error:

```
node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeDisableMultiregionAccessPointConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeUseArnRegionConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
```

## Your environment
macOs

#### SDK version number
`@aws-sdk/client-eventbridge": "3.51.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
Paste output of `npx envinfo --browsers` or `node -v` or `react-native -v`
node 14.18.2
npm 6.14.15

## Steps to reproduce
Please share code or minimal repo, and steps to reproduce the behavior.
update to 3.51.0 and run tsc to type check the project.

#### Observed behavior
I get type errors:

```
node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeDisableMultiregionAccessPointConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@aws-sdk/middleware-bucket-endpoint/dist-types/NodeUseArnRegionConfigOptions.d.ts:1:39 - error TS2307: Cannot find module '@aws-sdk/node-config-provider' or its corresponding type declarations.

1 import { LoadedConfigSelectors } from "@aws-sdk/node-config-provider";
```

#### Expected behavior
being able to to type check my project without raising errors

**Comment by trivikr** [comment]
I visited this issue while working on https://github.com/aws/aws-sdk-js-v3/pull/3334

I can see the types for `@aws-sdk/node-config-provider@3.51.0`

```console
$ yarn add @aws-sdk/node-config-provider@3.51.0 --exact
...

$ ls node_modules/@aws-sdk/node-config-provider/dist-types 
configLoader.d.ts		fromSharedConfigFiles.d.ts	index.d.ts
fromEnv.d.ts			fromStatic.d.ts			ts3.4
```

Our Support engineer will look into this issue.

**Comment by justintemps** [comment]
@trivikr any progress on this?

**Comment by justintemps** [comment]
Nope @ajredniwja this seems fixed with the latest version. Thanks!
