### PR TITLE
chore: add updated RDS DATA smithy model

### PR DESCRIPTION
**Pull request by AllanFly120**
* header default middleware
* expect continue middleare

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AllanFly120** [comment]
Well, I have to update all middlewares to pass the CI

**Comment by srchase** [comment]
The shapes are failing in a few places:

1. This one can be resolved by moving to TypeScript 3.7 (tested against Version 3.7.0-dev.20190926)
```
models/com/amazon/rdsdataservice.ts(31,15): error TS2339: Property 'stringValues' does not exist on type 'Pick<UnknownVariant & { stringValues?: string[] | undefined; booleanValues?: boolean[] | undefined; arrayValues?: Pick<UnknownVariant & ..., never>[] | undefined; blobValues?: Uint8Array[] | undefined; doubleValues?: number[] | undefined; longValues?: number[] | undefined; }, never>'.
```

2. Need to update how SmithyException is extending from Error
```
models/com/amazon/rdsdataservice.ts(48,12): error TS2416: Property 'message' in type 'BadRequestException' is not assignable to the same property in base type 'SmithyException'.
  Type 'string | undefined' is not assignable to type 'string'.
    Type 'undefined' is not assignable to type 'string'.
```

3. Record is a reserved word.  The type is aliased to _Record.  Record needs to be aliased when referenced within another structure.
```
models/com/amazon/rdsdataservice.ts(378,28): error TS2314: Generic type 'Record' requires 2 type argument(s).
```

4. Needs further research. Still does not work with 3.7.
```
models/com/amazon/rdsdataservice.ts(503,13): error TS2456: Type alias 'Value' circularly references itself.
```

**Comment by mtdowling** [comment]
> Need to update how SmithyException is extending from Error (resolved in awslabs/smithy-typescript#3)

Fixed in generator

> Record is a reserved word. The type is aliased to _Record. Record needs to be aliased when referenced within another structure. (resolved in awslabs/smithy-typescript#3)

Fixed in generator

**Comment by AllanFly120** [comment]
> Record is a reserved word. The type is aliased to _Record. Record needs to be aliased when referenced within another structure. (resolved in awslabs/smithy-typescript#3)

Just updated the PR with newest model. The `_Record` class is not referenced anywhere. Is this expected?

File: clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts [hunk 1]
```diff
@@ -0,0 +1,214 @@
...
+    }
+  });
+}
+
+export function executeStatementAwsRestJson1_1Deserialize(
+  output: HttpResponse
+): ExecuteStatementResponse {
+  let data: any = {};
+  if (output.body) {
+    data = JSON.parse(output.body);
```
Comment (AllanFly120) [inline clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts]: Here the `output.body` is not a binary data. It's actually `Readable` in node and `Blob` in browser. You should call streamcollector transfer them into binary. Example can be found here: https://github.com/aws/aws-sdk-js-v3/blob/226e54407c4979be935d44fb3afdc32fb4154683/packages/protocol-rest/src/RestParser.ts#L215-L234, You may need to import a runtime-specific stream collector like [node collector](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/stream-collector-node) and [browser collector](https://github.com/aws/aws-sdk-js-v3/tree/master/packages/stream-collector-browser)

File: clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+    path: "/execute",
+    method: "POST",
+    protocol: "https:",
+    headers: {
+      "Content-Type": "application/json"
+    }
+  });
+}
+
+export function executeStatementAwsRestJson1_1Deserialize(
```
Comment (AllanFly120) [inline clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts]: Deserializers should be async functions that return a promise according to [our definition](https://github.com/AllanFly120/aws-sdk-js-v3/blob/c60241b224457f94c33f6b3dc47ba5f9a0a175e6/packages/types/src/unmarshaller.ts#L26)

**Comment by AllanFly120** [comment]
The (de)serializer looks good to me. 🚢

File: clients/node/client-rds-data-node/lib/smithy.ts [hunk 3]
```diff
@@ -0,0 +1,44 @@
+export const TYPE = "__type";
```
Comment (mtdowling) [inline clients/node/client-rds-data-node/lib/smithy.ts]: I think we could move this file into a shared package in the future. This is fine for now.

File: clients/node/client-rds-data-node/package.json [hunk 4]
```diff
@@ -68,6 +69,6 @@
     "rollup-plugin-replace": "^2.2.0",
     "rollup-plugin-sourcemaps": "^0.4.2",
     "typedoc": "^0.14.2",
-    "typescript": "~3.4.0"
+    "typescript": "^3.7.0-dev.20190926"
```
Comment (mtdowling) [inline clients/node/client-rds-data-node/package.json]: Probably shouldn't rely on a dev build

File: clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts [hunk 5]
```diff
@@ -0,0 +1,297 @@
...
+  SqlParameter
+} from "../models/rdsdataservice";
+import { HttpRequest, HttpResponse } from "@aws-sdk/protocol-http";
+import * as __aws_sdk_stream_collector_node from "@aws-sdk/stream-collector-node";
+import * as __aws_sdk_util_utf8_node from "@aws-sdk/util-utf8-node";
+
+export function executeStatementAwsRestJson1_1Serialize(
+  input: ExecuteStatementRequest
+): HttpRequest {
+  let body: any = {};
```
Comment (mtdowling) [inline clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts]: A performance improvement here would be to use a streaming JSON serializer rather than needing to store the JSON object in an intermediate value. This should be done at some point but isn't a blocker right now.

File: clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts [hunk 6]
```diff
@@ -0,0 +1,297 @@
...
+      data.columnMetadata
+    ),
+    numberOfRecordsUpdated: data.numberOfRecordsUpdated,
+    generatedFields: generatedFieldsAwsRestJson1_1Deserialize(
+      data.generatedFields
+    )
+  });
+}
+
+function executeStatementAwsRestJson1_1DeserializeError(
```
Comment (mtdowling) [inline clients/node/client-rds-data-node/protocol/AwsRestJson1_1.ts]: I think this needs work. It should check the x-amzn-ErrorType header for the ID of the error and use that. If that's not found, then it should fall back to status codes.
