### ISSUE TITLE
TypeError: null is not a function when calling client.send 

### ISSUE THREAD

**Issue by farzadali3** [aws/aws-sdk-js-v3#6283]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I get the error `TypeError: null is not a function` when I use the send command on my s3Client, I have tested it with multiple commands and the issue persists. I have added the following polyfills. I am passing the correct keys.

```js
import 'react-native-url-polyfill/auto';
import 'react-native-get-random-values';
import {ReadableStream} from 'web-streams-polyfill';
(globalThis as any).ReadableStream = ReadableStream;
```
Here is my client initialization code

```js
import {S3Client, S3ClientConfig} from '@aws-sdk/client-s3';
import {AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_REGION} from '@env';

export default function s3Client() {
  const config: S3ClientConfig = {
    region: AWS_REGION,
    credentials: {
      accessKeyId: AWS_ACCESS_KEY_ID,
      secretAccessKey: AWS_SECRET_ACCESS_KEY,
    },
  };

  const client = new S3Client(config);

  return client;
}
```

### SDK version number

@aws-sdk/client-s3@3.614.0

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.74.1

### Reproduction Steps

It is quite simple to reproduce the issue, just use the S3 client to send any command. 
For example, let's use the command to list objects in a bucket

```js
import { S3Client, ListObjectsV2Command } from "@aws-sdk/client-s3";

// Create an S3 client
const s3 = new S3Client({ region: REGION });

const bucketParams = { Bucket: "my-bucket" };

const listObjectsCommand = new ListObjectsV2Command(bucketParams);

s3.send(listObjectsCommand)
  .then((data) => {
    console.log("Success", data);
  })
  .catch((err) => {
    console.error(err);
  });
```

### Observed Behavior

`TypeError: null is not a function`

Sometimes I also get: `TypeError: client.send is not a function`

When i used V2 which is `aws-sdk`, everything works fine, but it will be deprecated soon.

### Expected Behavior

We should be able to send any of the command.

### Possible Solution

I have no idea of the fix.

**Comment by farzadali3** [comment]
> ~Same issue with `@aws-sdk/client-cognito-identity-provider`. After upgrading to React Native `0.74.x`. Everything seemed to work okay with React Native `0.73.x` and below.~
> 
> ~I'm really not sure what might have broken the AWS SDK v3 but [here is a link to the release notes](https://reactnative.dev/blog/2024/04/22/release-0.74).~
> 
> Downgraded to React Native `0.73.8` and the issue is still there. I had upgraded the AWS SDK v3 lib at the same time so I'm going to start rolling that back until it works again.

You could downgrade to v2 (I can confirm it works fine) so that you can avoid getting blocked by this issue until we get an official response.

**Comment by farzadali3** [comment]
> @farzadali3 I can confirm React Native `0.74.3` and AWS SDK v3 `3.567.0` work.
> 
> I'm going to start upgrading the AWS SDK v3 until it stops working to try and identify where it broke.

Great @david-gettins! I'll await your confirmation regarding the latest functioning version. I won't close this issue yet, as it's crucial for the official team to be aware of and rectify the problem in the most recent release.

**Comment by david-gettins** [comment]
The issue crops up in `3.575.0` so the last version that worked in React Native was `3.574.0`.

**Comment by farzadali3** [comment]
Here are all the [changes](https://github.com/aws/aws-sdk-js-v3/compare/v3.574.0...v3.575.0) that were made from `3.574.0` to `3.575.0`. I also think it has something to do with Smithy.

**Comment by aBurmeseDev** [comment]
Hey all - thanks for reaching out. 

We've received [this recent report](https://github.com/aws/aws-sdk-js-v3/issues/6269) with same error importing `web-streams-polyfill` on React Native with AWS SDK. There are a few things we noticed with changes on `web-streams-polyfill` version `v3.3.3` and `v4.0.0`. While we further look into it, can you provide detailed steps to reproduce with React Native as this seems to be only specific with React Native?

**Comment by farzadali3** [comment]
Thank you for picking up the issue @aBurmeseDev. I can confirm the issue is specific to React Native as I was unable to reproduce it in a React app/Browser.

It's very easy to reproduce the issue, you can start by creating a new react native project by executing the command:
`npx @react-native-community/cli@latest init AwesomeProject`

You would have to install the S3 client by running:
`npm i @aws-sdk/client-s3`

The AWS SDK V3 requires the following polyfills in a React Native app:

```
import 'react-native-url-polyfill/auto';
import 'react-native-get-random-values';
import {ReadableStream} from 'web-streams-polyfill';
(globalThis as any).ReadableStream = ReadableStream;
```

You can run this command to install these:

`npm install react-native-url-polyfill react-native-get-random-values web-streams-polyfill`

Now, we need to initialize the S3 client and then send any command.

```
import { S3Client, S3ClientConfig, ListBucketsCommand, ListObjectsCommand } from '@aws-sdk/client-s3';

export default function s3Client() {
  const config: S3ClientConfig = {
    region: AWS_REGION,
    credentials: {
      accessKeyId: AWS_ACCESS_KEY_ID,
      secretAccessKey: AWS_SECRET_ACCESS_KEY,
    },
  };

  return new S3Client(config);
}

// Use the S3 client to list all buckets
const listAllBuckets = async () => {
  const client = s3Client();
  const command = new ListBucketsCommand({});
  const response = await client.send(command);
  console.log(response.Buckets);
};

// Use the S3 client to list all objects in a bucket
const listObjectsInBucket = async (bucketName: string) => {
  const client = s3Client();
  const command = new ListObjectsCommand({ Bucket: bucketName });
  const response = await client.send(command);
  console.log(response.Contents);
};
```

**Comment by aBurmeseDev** [comment]
@farzadali3 - please see my repro attempt and findings in [this comment](https://github.com/aws/aws-sdk-js-v3/issues/6269#issuecomment-2232288739) and since this's duplicate issue, I'm going to close it in favor of the other one and we can track it there.
