### ISSUE TITLE
Few librairies are not published in esmodule

### ISSUE THREAD

**Issue by superCarton** [aws/aws-sdk-js-v3#1476]
**Describe the bug**
When building a typescript application with a dependency on aws-amplify v3, there is a runtime exception when the library is calling a function on @aws-sdk/credential-provider-cognito-identity package.
It happened after a migration from aws-amplify v2 to v3.

**Is the issue in the browser/Node.js/ReactNative?**
Browser

**To Reproduce (observed behavior)**
Typescript application compiling with es module. A simple login will call a function on @aws-sdk/credential-provider-cognito-identity that will throw a "Object(...) is not a function" exception.

**Expected behavior**
The ES module should be published on NPM. Today, only the CJS module is published. This is weird because a quick inspection of the package.json of @aws-sdk/credential-provider-cognito-identity shows that the build in ES is planned, it is probably ignored during the package publishing.

**Comment by trivikr** [comment]
Amplify v3 still depends on gamma.4 version of SDK https://github.com/aws-amplify/amplify-js/search?q=aws-sdk+filename%3Apackage.json&unscoped_q=aws-sdk+filename%3Apackage.json

ESM version of `@aws-sdk/credential-provider-cognito-identity` was published in `1.0.0-gamma.6` verified as follows:
```console
$ yarn add @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.6
...
$ ls node_modules/@aws-sdk/credential-provider-cognito-identity/dist/ 
cjs	es
```

**Comment by trivikr** [comment]
The latest JS SDK v3 version is [v1.0.0-gamma.7](https://github.com/aws/aws-sdk-js-v3/releases/tag/v1.0.0-gamma.7)

@superCarton Are there specific modules which are missing ESM versions in gamma.7?

**Comment by superCarton** [comment]
@trivikr actually v1.0.0-gamma.4 does not contain ESM but v1.0.0-gamma.6 does
`$ yarn add @aws-sdk/credential-provider-cognito-identity@1.0.0-gamma.4
$ ls node_modules/@aws-sdk/credential-provider-cognito-identity/dist
cjs`

**Comment by trivikr** [comment]
> actually v1.0.0-gamma.4 does not contain ESM but v1.0.0-gamma.6 does

Yup. As explained in the previous comments, AWS Amplify v3 needs to update to v1.0.0-gamma.6 or above.
Do you want to create an issue with their repo at https://github.com/aws-amplify/amplify-js?

**Comment by superCarton** [comment]
Issue opened on amplify-js to bump the aws-sdk packages. Thanks @trivikr for you help!
