### ISSUE TITLE
AWS SDK 3 TypeError: 0, util_user_agent_browser_1.createDefaultUserAgentProvider is not a function

### ISSUE THREAD

**Issue by JulianHillworth** [aws/aws-sdk-js-v3#6573]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

React Native Project 

utilising 
    @aws-sdk/client-cognito-identity-provider": "^3.654.0",
    @aws-sdk/client-dynamodb": "^3.654.0",
    @aws-sdk/client-s3": "^3.654.0",
    @aws-sdk/client-sns": "^3.654.0",
    @aws-sdk/client-sqs": "^3.654.0",
    @aws-sdk/credential-provider-cognito-identity": "^3.654.0",
     amazon-cognito-identity-js": "^6.3.12

Patched to 

@aws-sdk/client-cognito-identity-provider       3.670.0  
@aws-sdk/client-dynamodb                              3.670.0 
@aws-sdk/client-s3                                            3.673.0
@aws-sdk/client-sns                                          3.670.0  
@aws-sdk/client-sqs                                          3.670.0
@aws-sdk/credential-provider-cognito-identity    3.670.0

npx expo run:android  builds correctly.  No issues on previous versions.

After applying updates and running npx expo run:android it also builds correctly once again.

When running the project receive error

TypeError: 0, util_user_agent_browser_1.createDefaultUserAgentProvider is not a function

This occurs on @aws-sdk/client-cognito-identity-provider  and @aws-sdk/client-sns from what I can tell.

Uninstall modules reinstall previous versions. works correctly.  Nothing else has changed in the project.  Merely updating the AWS modules.

### Regression Issue

- [X] Select this option if this issue appears to be a regression.

### SDK version number

AWS-SDK-JS-V3

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

0.74.5

### Reproduction Steps

To reproduce, run a build with the new patched dependencies compared to the previous.

### Observed Behavior

AWS services  @aws-sdk/client-cognito-identity-provider and @aws-sdk/client-sns will not work in the project.

### Expected Behavior

To continue operation as per version updated from.

### Possible Solution

What was changed, change back.

### Additional Information/Context

Nil

**Comment by aBurmeseDev** [comment]
Hi @JulianHillworth - thanks for reaching out. 

Could you please confirm the issue with the latest release `v3.674.0` and provide a minimal reproducible code snippet along with the error log? This will help us investigate and address the problem more effectively.

**Comment by catarinadasilva** [comment]
I've had the same error, I've upgraded the react native version from 0.67.5 to 0.75.3 and the issue started appearing when trying to boot a Client using new CloudWatchLogsClient: to reproduce, start a new react native app and create a dummy file that only calls the client, is enough to trigger the error on newer react native versions...

**Comment by aBurmeseDev** [comment]
Thanks for the response. You stated that the last working version is `3.654.0`, but an error arose in version `3.670.0`. Could you please confirm if the issue persists or has been resolved in the latest release, which is version `3.674.0`? Additionally, I would appreciate if you could provide your SDK code snippet, as I haven't been able to replicate the problem you're encountering with the S3 `ListObjectsCommand` when testing it with React Native version `0.75.3`.

**Comment by catarinadasilva** [comment]
Hello @aBurmeseDev, the issue seems to be incompatibility with the react native above 0.74... I've done the following and was able to reproduce:
```
npx react-native@latest init Test --skip-install
yarn add @aws-sdk/client-cloudwatch-logs
```
Then I've added the following to App.tsx
```
import {
  CloudWatchLogsClient,
} from '@aws-sdk/client-cloudwatch-logs';
...
  useEffect(() => {
    new CloudWatchLogsClient({
      region: 'us-east-1',
    });
  }, []);
```
And got this error
<img width="378" alt="Screenshot 2024-10-17 at 11 02 58 PM" src="https://github.com/user-attachments/assets/ca38652b-1daa-4426-ac8b-75fead88b385">

**Comment by catarinadasilva** [comment]
The issue happens in both Android and iOS builds (the previous screenshot is iOS)
In android shows this (is the same error)
<img width="978" alt="Screenshot 2024-10-17 at 11 10 07 PM" src="https://github.com/user-attachments/assets/8f134649-27ee-4fd5-9e1f-db3d58e1fe7b">

**Comment by aBurmeseDev** [comment]
Can you add the following polyfills and give it another try?
`npm install react-native-get-random-values react-native-url-polyfill web-streams-polyfill`
```js
import "react-native-get-random-values";
import "react-native-url-polyfill/auto";
import "web-streams-polyfill/dist/polyfill";
```

It's mentioned in our [README](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md#getting-started) that react-native environment requires certain polyfills to work with SDK:
>If you are consuming modular AWS SDK for JavaScript on react-native environments, you will need to add and import following polyfills in your react-native application:
>
>[react-native-get-random-values](https://www.npmjs.com/package/react-native-get-random-values)
>[react-native-url-polyfill](https://www.npmjs.com/package/react-native-url-polyfill)
>[web-streams-polyfill](https://www.npmjs.com/package/web-streams-polyfill)

**Comment by catarinadasilva** [comment]
Same thing, even with those imports in the index.js the builder version can't access the createDefaultUserAgentProvider...
<img width="432" alt="Screenshot 2024-10-17 at 11 16 31 PM" src="https://github.com/user-attachments/assets/bec8cf3e-fd3d-4ba0-80f7-ae1b0757211b">
<img width="389" alt="Screenshot 2024-10-17 at 11 16 40 PM" src="https://github.com/user-attachments/assets/101abd9d-5454-404f-b0c7-0f81938085b6">
<img width="368" alt="Screenshot 2024-10-17 at 11 16 46 PM" src="https://github.com/user-attachments/assets/1970e373-aaa7-48d5-96cd-6dd2b24a5cb5">
<img width="433" alt="Screenshot 2024-10-17 at 11 16 51 PM" src="https://github.com/user-attachments/assets/8206f65b-aa0f-46d1-89f9-2e590ac6439d">

**Comment by catarinadasilva** [comment]
**There is an important note:** this issue seems to happen to all versions above 3.398.0 of the aws-sdk-js-v3.

The @aws-sdk/client-cloudwatch-logs was working with react native 0.67.5, but since the upgrade to the latest react-native version the issue started...

I've tried to rollback to react-native 0.67.5 and it started working again, however, we can't use that react-native version as Android requires a patch that's only available on versions above 0.72

**Comment by aBurmeseDev** [comment]
Appreciate the additional details. A few more questions to verify before further investigation:
- have you worked with other clients and is it same issue for all service clients or just CloudWatchLogsClient?
- you stated that this issue started beyond version `3.398.0` of SDK which was [released](https://github.com/aws/aws-sdk-js-v3/releases?q=%223.398.0%22&expanded=true) in Aug 2023. Can you verify that was the last working version?

**Comment by catarinadasilva** [comment]
>have you worked with other clients and is it same issue for all service clients or just CloudWatchLogsClient?

We only using Cloudwatch logs, but I believe this happens in all clients with react native 0.7x

>you stated that this issue started beyond version 3.398.0 of SDK which was [released](https://github.com/aws/aws-sdk-js-v3/releases?q=%223.398.0%22&expanded=true) in Aug 2023. Can you verify that was the last working version?

I don't think the issue is directly related with the SDK version but an incompatibility with the newer versions of react-native, the 3.398.0 works on react-native 0.67.5 but not in 0.7x such as 0.75.3

**Comment by JulianHillworth** [comment]
> Hi @JulianHillworth - thanks for reaching out.
> 
> Could you please confirm the issue with the latest release `v3.674.0` and provide a minimal reproducible code snippet along with the error log? This will help us investigate and address the problem more effectively.

Hi, just tried it on cognito-identity-provider v3.674.  Same issue.  Revert it back to 3.654 works.  Confirmed I have the polyfills installed.

Code snippet

```
const handleGetUserCommand = async (accessToken: string) => {
  try {
    const command = new GetUserCommand({
      AccessToken: accessToken,
    });
    const response = await cognitoClient.send(command);
    return response;
  } catch (error) {
    console.log(`handleGetUserCommand error: `, error);
    return null;
  }
};
```

TypeError: 0, util_user_agent_browser_1.createDefaultUserAgentProvider is not a function (it is undefined), js engine: hermes

![image](https://github.com/user-attachments/assets/4e6fa314-8d72-4363-9535-f13fecc4bdf1)

**Comment by aBurmeseDev** [comment]
Thank you for providing comprehensive details; it assisted me in my testing process. After evaluating multiple versions, I have identified that `v3.669.0` is the latest compatible version, while it appears that `v3.670.0` introduced an incompatibility issue. While we further investigate, please remain on `v3.669.0`.

**Comment by catarinadasilva** [comment]
Hello @aBurmeseDev, thanks for the help.

I've confirmed that version 3.669.0 does not trigger the error, we will remain on that version temporarily while you and your team fix the issue on a new version containing all the patches between 3.669.0 and 3.674.

**Comment by aman-saraf** [comment]
@aBurmeseDev ,  this issue is happening on @aws-sdk/client-scheduler 3.674.0 as well. I tried downgrading the library to lower versions such as v3.670.0 , v3.665.0, but it's still not working. When I investigated the package-lock.json file, it was still downloading the v3.674.0 zip from npm even for the lower versions and even after deleting the package lock and node modules.

**Comment by kevincarpdev** [comment]
@catarinadasilva - thank you for your troubleshooting. 
I encountered the same error today. 
Downgrading to 3.669.0 worked for me as well.

**Comment by aBurmeseDev** [comment]
Hi @catarinadasilva! Quick update; the fix was [released](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.675.0) in `v3.675.0` and I've verified it on my end.

However, if anyone's still see the issue after upgrading to version `3.675.0`, it is recommended that you remove the node_modules directory and/or the package-lock file, and then reinstall the required packages. This step can often resolve lingering issues related to dependencies and package versions.

Thanks again for reporting this!

**Comment by catarinadasilva** [comment]
Hello @aBurmeseDev, I can confirm that the version `3.675.0`, does not have the original issue of this thread, however, the logs are not reaching cloudwatch, not sure where they are being sent but it seems that's not using the configurations parsed to the client, at least there are no changes on the code aside the npm install of the latest version.

**Comment by aBurmeseDev** [comment]
@catarinadasilva - appreciate the update and glad the issue is now resolved. 

@sqrter - remove the node_modules directory and/or the package-lock file, and then reinstall the required packages. There might be lingering issues between dependencies and package versions.

**Comment by sqrter** [comment]
@aBurmeseDev Though reinstalling didn't help, I found where the problem was - in transitive dependencies. I had a resolution configuration for one of my dependencies, and one of its transitive dependencies was also used in `@aws-sdk` which led to the incorrect behavior. Thanks

**Comment by tomoima525** [comment]
Seems like this issue is still happening with node.js Lambda . Everything is freshly installed in my environment.

version: 3.679.0

![image](https://github.com/user-attachments/assets/b16366d6-5870-41b5-82d5-db1423739882)


```
{
  "errorType": "TypeError",
  "errorMessage": "(0 , util_user_agent_node_1.createDefaultUserAgentProvider) is not a function",
  "trace": [
    "TypeError: (0 , util_user_agent_node_1.createDefaultUserAgentProvider) is not a function",
    "    at getRuntimeConfig (/opt/nodejs/node_modules/email-layer/node_modules/@aws-sdk/client-sqs/dist-cjs/runtimeConfig.js:34:71)",
    "    at new SQSClient (/opt/nodejs/node_modules/email-layer/node_modules/@aws-sdk/client-sqs/dist-cjs/index.js:186:65)",
    "    at new SQS (/opt/nodejs/node_modules/email-layer/node_modules/@aws-sdk/client-sqs/dist-cjs/index.js:2261:12)",
```

**Comment by srdjanbogicevic** [comment]
I have the same problem, tried with new versions like 3.674.0, 3.675.0, 3.679.0 but it does not work. 
Downgraded to 3.437.0 and it works now!

I am using: 
"@aws-sdk/client-firehose": "3.437.0",
"@aws-sdk/client-s3": "3.437.0",
"@aws-sdk/s3-request-presigner": "3.437.0",

in NextJS project deployed as standalone service on ubuntu server. Node version is v18.17.0.
