### ISSUE TITLE
DynamoDBClient endpoint typings are broken by #4078

### ISSUE THREAD

**Issue by birtles** [aws/aws-sdk-js-v3#4086]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

The following code used to work:

```typescript
export const ddbClient = new DynamoDBClient({
  endpoint: {
    hostname: 'localhost',
    path: '/',
    protocol: 'http',
    port: 8090,
  },
  tls: false,
  region: 'local-env',
});
```

As of 3.195.0 it errors with:

```
src/database/ddb-client.ts:6:3 - error TS2322: Type '{ hostname: string; path: string; protocol: string; port: number; }' is not assignable to type '((string | Endpoint | Provider<Endpoint> | EndpointV2 | Provider<EndpointV2>) & (string | Provider<string>)) | undefined'.
  Type '{ hostname: string; path: string; protocol: string; port: number; }' is not assignable to type 'Endpoint & Provider<string>'.
    Type '{ hostname: string; path: string; protocol: string; port: number; }' is not assignable to type 'Provider<string>'.
      Type '{ hostname: string; path: string; protocol: string; port: number; }' provides no match for the signature '(): Promise<string>'.

6   endpoint: {
    ~~~~~~~~

  node_modules/@aws-sdk/middleware-endpoint/dist-types/resolveEndpointConfig.d.ts:12:5
    12     endpoint?: string | Endpoint | Provider<Endpoint> | EndpointV2 | Provider<EndpointV2>;
           ~~~~~~~~
    The expected type comes from property 'endpoint' which is declared here on type 'DynamoDBClientConfig'
```

### SDK version number

@aws-sdk/client-dynamodb@3.195.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v16.16.0

### Reproduction Steps

(See description above.)

### Observed Behavior

(See description above.)

### Expected Behavior

The code should continue to be accepted by the type checker as it was in 3.194.0.

### Additional Information/Context

It appears #4078 changed the typing for `DynamoDBClientConfigType` as follows:

```diff
 type DynamoDBClientConfigType = Partial<__SmithyConfiguration<__HttpHandlerOptions>> &
   ClientDefaults &
   RegionInputConfig &
-  EndpointsInputConfig &
+  EndpointInputConfig<EndpointParameters> &
   RetryInputConfig &
   HostHeaderInputConfig &
   AwsAuthInputConfig &
   UserAgentInputConfig &
-  EndpointDiscoveryInputConfig;
+  EndpointDiscoveryInputConfig &
+  ClientInputEndpointParameters;
```

`EndpointInputConfig<EndpointParameters>` defines an `endpoint` member as:

```typescript
    endpoint?: string | Endpoint | Provider<Endpoint> | EndpointV2 | Provider<EndpointV2>;
```

where `Endpoint` is:

```typescript
export interface Endpoint {
    protocol: string;
    hostname: string;
    port?: number;
    path: string;
    query?: QueryParameterBag;
}
```

whereas `ClientInputEndpointParameters` _also_ defines an `endpoint` member as:

```typescript
    endpoint?: string | Provider<string>;
```

Because `EndpointInputConfig<EndpointParameters>` and `ClientInputEndpointParameters` are `&`-ed together, Typescript expects the type of `endpoint` to be `((string | Endpoint | Provider<Endpoint> | EndpointV2 | Provider<EndpointV2>) & (string | Provider<string>)) | undefined` and hence code using the `Endpoint` type is no longer accepted.

**Comment by kuhe** [comment]
This should be fixed as of https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.197.0
