### ISSUE TITLE
getSignedUrl does not work with TypeScript in v3.12.0

### ISSUE THREAD

**Issue by euangoddard** [aws/aws-sdk-js-v3#2235]
## Describe the bug
Since upgrading from v 3.11.0 to v 3.12.0 of the packages `@aws-sdk/client-s3` and `@aws-sdk/s3-request-presigner` the following code (taken from the official documentation) work:

```typescript
const client = new S3Client(clientParams);
const command = new GetObjectCommand(getObjectParams);
const url = await getSignedUrl(client, command, { expiresIn: 3600 });
```

It gives the following TypeScript error:

```
error TS2345: Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
```

## Your environment

Node 14 (via NVM on MacOS), TypeScript 4.2.4

#### SDK version number
`@aws-sdk/client-s3@3.12.0` and `@aws-sdk/s3-request-presigner@3.12.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v14.15.3

## Steps to reproduce
Please see note above of the code required to break this (note TypeScript is running with `strict: true`

#### Observed behavior

Full error from TypeScript:

```
error TS2345: Argument of type 'S3Client' is not assignable to parameter of type 'Client<any, ServiceInputTypes, MetadataBearer, any>'.
  The types of 'middlewareStack.concat' are incompatible between these types.
    Type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>'.
      Types of parameters 'from' and 'from' are incompatible.
        Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, ServiceOutputTypes>'.
          Types of property 'addRelativeTo' are incompatible.
            Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, ServiceOutputTypes>, options: RelativeMiddlewareOptions) => void'.
              Types of parameters 'middleware' and 'middleware' are incompatible.
                Type 'MiddlewareType<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                  Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                    Type 'InitializeMiddleware<InputType, ServiceOutputTypes>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                      Call signature return types 'InitializeHandler<InputType, ServiceOutputTypes>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                        Type 'Promise<InitializeHandlerOutput<ServiceOutputTypes>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                          Type 'InitializeHandlerOutput<ServiceOutputTypes>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                            Types of property 'output' are incompatible.
                              Type 'ServiceOutputTypes' is not assignable to type 'OutputType'.
                                'ServiceOutputTypes' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
                                  Type 'MetadataBearer' is not assignable to type 'OutputType'.
                                    'MetadataBearer' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'MetadataBearer'.
```

#### Expected behavior
The code should work as per the example in your documentation _and_ as it worked in V3.11.0

#### Screenshots
N/A

**Comment by AllanZhengYP** [comment]
Hi @euangoddard 

Can you make sure all the `@aws-sdk/xxx` dependencies in the package.json is the same version? This is not required for using SDK, but will help me finding the root cause.

**Comment by euangoddard** [comment]
I am now using v3.13.1 of the SDK (all sub-module dependencies) and this issue appears to be resolved. Thanks!
