### ISSUE TITLE
unable to follow documentation to write integration tests for S3 read/write

### ISSUE THREAD

**Issue by LukasGlader** [aws/aws-sdk-js-v3#6241]
### Describe the issue

After upgrading my npm dependency of @smithy/util-stream from 2.0.2 to 3.0.5 I started getting compilation errors in my S3 integration tests related to the mockClient. Googling around for the error message proved unfruitful, and searching for guides on how to build S3 integration tests finally led me to the following page which contains code that does not help me but provides an example of how to replicate the issue:
https://m-radzikowski.github.io/aws-sdk-client-mock/#md:s3-getobjectcommand

The issue is that the sdkStreamMixin function no longer returns an object that is compatible with the Body field needed in the parameter to .resolves(), resulting in the following error message:

TS2322: Type
SdkStream<Blob | ReadableStream> | SdkStream<Readable>
is not assignable to type StreamingBlobPayloadOutputTypes | undefined

The only resources I have been able to find on integration testing on your website is the following:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_cross_Testing_section.html
which is for Rust.
The documentation for @smithy/util-stream on your website
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-util-stream/
contains nothing at all, neither does the npm package page for it: https://www.npmjs.com/package/@smithy/util-stream
and the README at the GitHub page: https://github.com/smithy-lang/smithy-typescript doesn't contains anything useful either.
Would it be possible for you to improve the documentation on how to create integration tests with node+typescript?

### Links

https://docs.aws.amazon.com/AmazonS3/latest/userguide/example_cross_Testing_section.html
https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-smithy-util-stream/

**Comment by LukasGlader** [comment]
I just realised that the mockClient() function comes from another third party package aws-sdk-client-mock, and there is an issue open there: https://github.com/m-radzikowski/aws-sdk-client-mock/issues/227

Closing this issue, thanks for reading and hopefully this might help someone else in the future.

**Comment by LukasGlader** [comment]
I just realised that the mockClient() function comes from another third party package aws-sdk-client-mock, and there is an issue open there: https://github.com/m-radzikowski/aws-sdk-client-mock/issues/227

Closing this issue, thanks for reading and hopefully this might help someone else in the future.
