### ISSUE TITLE
Property '$metadata' does not exist on type 'StartExecutionCommandOutput'.

### ISSUE THREAD

**Issue by blindperson** [aws/aws-sdk-js-v3#4906]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

After upgrading from version 3.359.0 to 3.363.0, packaging errors were reported
 error TS2339: Property '$metadata' does not exist on type 'StartExecutionCommandOutput'.

### SDK version number

@aws-sdk/client-sfn@3.363.0,@aws-sdk/client-lambda@3.363.0,

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

v14.18.3

### Reproduction Steps

After upgrading from version 3.359.0 to 3.363.0, packaging errors were reported
 error TS2339: Property '$metadata' does not exist on type 'StartExecutionCommandOutput'.

### Observed Behavior

Compiling typescript...
```
command-forward-v1/test/commandForward.spec.ts(83,7): error TS2322: Type '{ StatusCode: number; $metadata: { httpStatusCode: number; }; }' is not assignable to type 'InvokeCommandOutput'.
  Object literal may only specify known properties, and '$metadata' does not exist in type 'InvokeCommandOutput'.
command-forward-v1/test/commandForward.spec.ts(148,7): error TS2322: Type '{ StatusCode: number; $metadata: {}; }' is not assignable to type 'InvokeCommandOutput'.
  Object literal may only specify known properties, and '$metadata' does not exist in type 'InvokeCommandOutput'.
command-forward-v1/test/commandForward.spec.ts(239,7): error TS2322: Type '{ StatusCode: number; $metadata: {}; }' is not assignable to type 'InvokeCommandOutput'.
  Object literal may only specify known properties, and '$metadata' does not exist in type 'InvokeCommandOutput'.
delete-repository-v4/src/utils/callStepFunction.ts(36,21): error TS2339: Property '$metadata' does not exist on type 'StartExecutionCommandOutput'.
```

### Expected Behavior

npm run build successfully

**Comment by aldirrix** [comment]
We are experiencing the same with the DynamoDB client

`Property '$metadata' does not exist on type 'DeleteItemCommandOutput'.`

**Comment by RanVaknin** [comment]
Hi @blindperson and @aldirrix ,

Can either of you please post some reproduction steps and code that can help us raise the same errors?

Thanks,
Ran~

**Comment by blindperson** [comment]
hi @RanVaknin 
I just uploaded a simple demo to GitHub, please help review, thanks：https://github.com/blindperson/aws-sdk-V3.363-test

**Comment by blindperson** [comment]
and after executing npm i && npm run build, i can get same error
```
[tsl] ERROR in C:\Users\t_xuez\Desktop\code\aws-sdk-V3.363-test\index.ts(19,21)
      TS2339: Property '$metadata' does not exist on type 'StartExecutionCommandOutput'.`

**Comment by blindperson** [comment]
hi @RanVaknin and aws team, do you have any update? thanks

**Comment by bossyan** [comment]
Any updates?
