### ISSUE TITLE
CloudFront createInvalidation Typescript error

### ISSUE THREAD

**Issue by paulrobello** [aws/aws-sdk-js-v3#2956]
## Describe the bug
Typescript project fails to compile when attempting to access Invalidation member of result returned from call using class CloudFront method createInvalidation

## Your environment
Windows 10 Pro and 11 Pro

#### SDK version number
@aws-sdk/client-cloudfront@3.37.0
and
@aws-sdk/client-cloudfront@3.38.0

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
node v16.13.0

## Steps to reproduce
import { CloudFront, CreateInvalidationCommandInput,
  CreateInvalidationCommandOutput } from '@aws-sdk/client-cloudfront';

const input: CreateInvalidationCommandInput = {
            DistributionId: cfDistributionId,
            InvalidationBatch: {
              CallerReference: buildHash,
              Paths: {
                Items: invalidationPaths,
                Quantity: invalidationPaths.length
              }
            }
};

const res:CreateInvalidationCommandOutput = await new CloudFront({ credentials: fromEnv() }).createInvalidation(input);
const invalidationId = res.Invalidation?.Id;

#### Observed behavior
TSError: ⨯ Unable to compile TypeScript:
infrastructure/cloudfront-invalidation-provider.ts(69,32): error TS2339: Property 'Invalidation' does not exist on type 'CreateInvalidationCommandOutput'.

#### Expected behavior
Clean compile

Confirmed working on @aws-sdk/client-cloudfront@3.36.0

**Comment by galamiram-walnut** [comment]
Thank you for opening this issue @paulrobello it helped me knowing the last working version.

**Comment by vudh1** [comment]
Hi @paulrobello, thanks for reaching out. I'm not able to reproduce it. Can you confirm if you still experience with this issue with the latest SDK version `3.42.0`?

**Comment by paulrobello** [comment]
Issue appears to be resolved in v3.42.0. 
Thank you for the heads up.
