### ISSUE TITLE
Cannot find module 'node:stream' or its corresponding type declarations.

### ISSUE THREAD

**Issue by michalgrochowski** [aws/aws-sdk-js-v3#7181]
### Checkboxes for prior research

- [x] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [x] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Hi,

After updating AWS-SDK from v2 to v3 I have a problem with Angular app build - I get an TS error from a @smithy/util-stream saying that module "node:stream" cannot be found. I've tried node v20, v21 and currently v22.17.0, but it's not the issue.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### SDK version number

@aws-sdk/credential-providers@3.840., @aws-sdk/lib-storage@3.842.0, @aws-sdk/xhr-http-handler@3.840.0, @aws-sdk/client-s3@3.664.0, @aws-sdk/s3-request-presigner@3.664.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Angular v18, Node.js v22.17.0, Chrome latest

### Reproduction Steps

Use Upload to observe 'httpUploadProgress' and PutObjectCommand using S3Client send() method

### Observed Behavior

Application cannot be run/build due to missing import/module

### Expected Behavior

Application should run/build as expected
