### ISSUE TITLE
Typescript 3.5.x breaking @aws-sdk/types

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#2022]
## Describe the bug
`@aws-sdk/types` uses `AsyncGenerator`
https://github.com/aws/aws-sdk-js-v3/blob/80a80941a150e36f416bb24cc6c137f674c1dbdf/packages/types/src/pagination.ts#L3-L6

The customer code throws `"Cannot find name 'AsyncGenerator'"` when trying to compile with TS <3.6.x
```console
$ tsc
node_modules/@aws-sdk/types/types/ts3.4/pagination.d.ts:5:36 - error TS2304: Cannot find name 'AsyncGenerator'.

5 export declare type Paginator<T> = AsyncGenerator<T, T, unknown>;
                                     ~~~~~~~~~~~~~~
Found 1 error.
```

#### SDK version number
`@aws-sdk/client-s3@3.4.1`

#### Is the issue in the browser/Node.js/ReactNative?
N/A

#### Details of the browser/Node.js/ReactNative version
Not relevant but, Node.js `v14.15.4`

## Steps to reproduce

<details>
<summary>package.json</summary>

```json
{
  "scripts": {
    "build": "tsc"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "3.4.1"
  },
  "devDependencies": {
    "@types/node": "14.14.25",
    "typescript": "3.5.3"
  }
}
```

</details>

<details>
<summary>tsconfig.json</summary>

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "strict": true,
    "esModuleInterop": true
  }
}
```

</details>

<details>
<summary>index.ts</summary>

```ts
import { S3Client } from "@aws-sdk/client-s3";
```

</details>

#### Observed behavior
```console
yarn build
yarn run v1.22.10
warning package.json: No license field
$ tsc
node_modules/@aws-sdk/types/types/ts3.4/pagination.d.ts:5:36 - error TS2304: Cannot find name 'AsyncGenerator'.

5 export declare type Paginator<T> = AsyncGenerator<T, T, unknown>;
                                     ~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

#### Expected behavior
No error is thrown when compiling client code with TypeScript version 3.5.x

## Additional context
Follow-up to https://github.com/aws/aws-sdk-js-v3/issues/1919

**Comment by trivikr** [comment]
One workaround is to unblock is to enable [`skipLibCheck`](https://www.typescriptlang.org/tsconfig#skipLibCheck) in TSConfig of application code.
This would skip type checking of all declaration files though.

**Comment by trivikr** [comment]
This happens as the `AsyncGenerator` was added in `es2018.asyncgenerator` which was release in TypeScript 3.6
* Code: https://github.com/microsoft/TypeScript/blob/v3.6-beta/lib/lib.es2018.asyncgenerator.d.ts
* PR which added it https://github.com/microsoft/TypeScript/pull/32578
