### ISSUE TITLE
Error `util_endpoints_1.getUserAgentPrefix is not a function`

### ISSUE THREAD

**Issue by kjschabra** [aws/aws-sdk-js-v3#4578]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Using `@aws-sdk/client-s3` at version 3.299.0, I am receiving the following error:
```
TypeError: (0 , util_endpoints_1.getUserAgentPrefix) is not a function
```

### SDK version number

@aws-sdk/client-s3@3.299.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

18.15.0

### Reproduction Steps

Steps to reproduce:
1. `npm i @aws-sdk/client-s3@3.299.0`
2. In code:
```js
import { S3Client, HeadBucketCommand } from '@aws-sdk/client-s3'
try {
  const client = new S3Client({
    credentials: { accesKeyId: 'aws-access-key', secretAccessKey: 'secret-access-key' },
    region: 'us-east-2'
  })
  await client.send(new HeadBucketCommand({ Bucket: 'test-bucket' }) )
} catch(err) {
  // Throw error mentioned at the top
  console.error(err) 
}
```

### Observed Behavior

<img width="1908" alt="Screen Shot 2023-03-24 at 8 22 29 PM" src="https://user-images.githubusercontent.com/2325085/227667316-0e76ec3d-b5d0-4412-99c8-630e64b96bae.png">

### Expected Behavior

Expected behaviour: Result of `HeadBucketCommand`

### Possible Solution

working in version `3.294.0`

`npm i aws-sdk/client-s3@3.294.0`

**Comment by sergio-toro** [comment]
I'm having the same issue with`@aws-sdk/client-eventbridge` with several different versions, the last that was working correctly is`3.289.0`

```
server-local [eventRepository] Initializing event emitter with settings {
  awsRegion: 'eu-central-1',
  awsEndpoint: 'http://127.0.0.1:4566',
  eventSource: 'oliva.local.events',
  eventBusName: 'oliva.local.events_bus'
} +0ms
server-local [eventProducer] Failed to execute event producer {
  error: TypeError: (0 , util_endpoints_1.getUserAgentPrefix) is not a function
      at /Users/sergio/oliva/univers/node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-user-agent/dist-cjs/user-agent-middleware.js:16:60
      at async /Users/sergio/oliva/univers/node_modules/@aws-sdk/client-eventbridge/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
      at async EventRepository.triggerEvent (/Users/sergio/oliva/univers/packages/business/src/Events/infrastructure/repositories/EventRepository.ts:46:22)
      at async handler (/Users/sergio/oliva/univers/apps/lambdas/src/manualEventProducer/index.ts:14:5)
      at async runLambda (/Users/sergio/oliva/univers/apps/lambdas/src/run.js:35:5)
} +179ms
```

**Comment by RanVaknin** [comment]
Hi @kjschabra, @sergio-toro , 

Unfortunately Im not able to reproduce the issue using the provided code.

Can you provide the content of your `package.json`? 
Can you try deleting `package-lock.json` and `node_modules`,  and then running `npm install`? 

Thanks,
Ran~

**Comment by kjschabra** [comment]
@RanVaknin ran a fresh install by removing `node_modules` dir and `yarn.lock`. Seems to work now. Thanks for this.

One thing I did notice, running `yarn` after removing `node_modules` and `yarn.lock` I ran into an issue of parsing JSON from the `@aws-sdk/middleware-retry` module. 
To fix this I had to do `npm i` and then `npm update` to update all packages. Removed `node_modules` and `package-lock.json`. And then did `yarn` to make things work again.

here's my `package.json` content:

```json
{
  "name": "repo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@auth0/nextjs-auth0": "^2.2.2",
    "@aws-sdk/client-cloudformation": "^3.241.0",
    "@aws-sdk/client-dynamodb": "^3.287.0",
    "@aws-sdk/client-s3": "^3.299.0",
    "@aws-sdk/lib-dynamodb": "^3.287.0",
    "@aws-sdk/types": "^3.296.0",
    "@headlessui/react": "^1.7.13",
    "@heroicons/react": "^2.0.16",
    "@next/font": "13.1.1",
    "@types/dashify": "^1.0.1",
    "@types/node": "18.11.18",
    "@types/react": "18.0.26",
    "@types/react-dom": "18.0.10",
    "array-move": "^4.0.0",
    "classnames": "^2.3.2",
    "dashify": "^2.0.0",
    "eslint": "^8.31.0",
    "eslint-config-next": "^13.2.4",
    "next": "13.1.1",
    "pascalcase": "^2.0.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "swr": "^2.1.0",
    "typescript": "4.9.4",
    "uuid": "^9.0.0"
  },
  "devDependencies": {
    "@faker-js/faker": "^7.6.0",
    "@types/pascalcase": "^1.0.1",
    "@types/uuid": "^9.0.1",
    "@typescript-eslint/eslint-plugin": "^5.57.0",
    "@typescript-eslint/parser": "^5.57.0",
    "autoprefixer": "^10.4.13",
    "babel-eslint": "^10.1.0",
    "eslint-config-airbnb": "^19.0.4",
    "eslint-config-node": "^4.1.0",
    "eslint-config-prettier": "^8.6.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-jsx-a11y": "^6.6.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.32.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "postcss": "^8.4.20",
    "prettier": "^2.8.1",
    "tailwindcss": "^3.2.4"
  }
}
```
